spring.application.name=restapi

spring.datasource.url=jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.zafbrmcfhwhnexfouisc
spring.datasource.password=yisndnon2ojfpxmnsle%&#
spring.datasource.driver-class-name=org.postgresql.Driver
# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect